### ISSUE TITLE
sed: /opt/pot/jails/base-11_1/custom/etc/crontab: No such file or directory

### ISSUE THREAD

**Issue by 0mp** [pizzamig/pot#35] opened 2018-05-18 12:23 UTC
Hi,

I'm trying out pot for the first time and I got the following error:

```console
$ sudo pkg install pot
$ sudo pkg init
$ sudo pot create-base -r 11.1
===>  Create a base with release 11.1
/tmp/11.1_base.txz                            100% of   99 MB  741 kBps 02m18s
===>  Create the zfs datasets for base release zroot/pot/bases/11.1
sed: /opt/pot/jails/base-11_1/custom/etc/crontab: No such file or directory
sed: /opt/pot/jails/base-11_1/custom/etc/crontab: No such file or directory
```

Then I tried to run `create-base` again:

```console
$ sudo pot create-base -r 11.1
===>  Create a base with release 11.1
===>  Create the zfs datasets for base release zroot/pot/bases/11.1
./sbin/init: Can't restore time
./lib/libcrypt.so.5: Can't restore time
./lib/libthr.so.3: Can't restore time
./lib/libc.so.7: Can't restore time
./usr/lib/librt.so.1: Can't restore time
./usr/bin/crontab: Can't restore time
./usr/bin/su: Can't restore time
./usr/bin/chpass: Can't restore time
./usr/bin/passwd: Can't restore time
./usr/bin/opieinfo: Can't restore time
./usr/bin/login: Can't restore time
./usr/bin/opiepasswd: Can't restore time
./libexec/ld-elf.so.1: Can't restore time
tar: Error exit delayed from previous errors.
cp: cannot overwrite directory opt/custom/etc/unbound with non-directory etc/unbound
cp: symlink: ../usr/sbin/rmt: File exists
cp: utimensat: opt/custom/var/empty: Operation not permitted
cp: symlink: ../usr/sbin/rmt: File exists
cp: symlink: ../var/unbound: File exists
cp: cannot overwrite directory opt/custom/var/db/etcupdate/current/usr/share/man/en.ISO8859-15 with non-directory var/db/etcupdate/current/usr/share/man/en.ISO8859-15
cp: symlink: ../man4: File exists
cp: symlink: ../man9: File exists
cp: symlink: ../man3: File exists
cp: symlink: ../man7: File exists
cp: symlink: ../man2: File exists
cp: symlink: ../man8: File exists
cp: symlink: ../man5: File exists
cp: symlink: ../man1: File exists
cp: symlink: ../man6: File exists
cp: symlink: ../man6: File exists
cp: symlink: ../man1: File exists
cp: symlink: ../man5: File exists
cp: symlink: ../man8: File exists
cp: symlink: ../man2: File exists
cp: symlink: ../man7: File exists
cp: symlink: ../man3: File exists
cp: symlink: ../man9: File exists
cp: symlink: ../man4: File exists
cp: symlink: C: File exists
cp: symlink: C: File exists
cp: cannot overwrite directory opt/custom/var/db/etcupdate/current/usr/share/openssl/man/en.ISO8859-15 with non-directory var/db/etcupdate/current/usr/share/openssl/man/en.ISO8859-15
cp: symlink: ../man3: File exists
cp: symlink: ../man1: File exists
cp: symlink: usr/src/sys: File exists
```

`sudo pot create -p shield -b 11.1` worked just fine, however, and now I'm in jail's shell.

---

**Details**:
 * FreeBSD 12.0-CURRENT  r333659 amd64
 * pot: 0.5.5
 * ZFS

**Comment by 0mp** [comment] 2018-05-18 12:28
I tried to run `create-base` again:

```console
$ sudo pot create-base -r 11.1
===>  Create a base with release 11.1
===>  Create the zfs datasets for base release zroot/pot/bases/11.1
./sbin/init: Can't restore time
./lib/libcrypt.so.5: Can't restore time
./lib/libthr.so.3: Can't restore time
./lib/libc.so.7: Can't restore time
./usr/lib/librt.so.1: Can't restore time
./usr/bin/crontab: Can't restore time
./usr/bin/su: Can't restore time
./usr/bin/chpass: Can't restore time
./usr/bin/passwd: Can't restore time
./usr/bin/opieinfo: Can't restore time
./usr/bin/login: Can't restore time
./usr/bin/opiepasswd: Can't restore time
./libexec/ld-elf.so.1: Can't restore time
tar: Error exit delayed from previous errors.
cp: cannot overwrite directory opt/custom/etc/unbound with non-directory etc/unbound
cp: symlink: ../usr/sbin/rmt: File exists
cp: utimensat: opt/custom/var/empty: Operation not permitted
cp: symlink: ../usr/sbin/rmt: File exists
cp: symlink: ../var/unbound: File exists
cp: cannot overwrite directory opt/custom/var/db/etcupdate/current/usr/share/man/en.ISO8859-15 with non-directory var/db/etcupdate/current/usr/share/man/en.ISO8859-15
cp: symlink: ../man4: File exists
cp: symlink: ../man9: File exists
cp: symlink: ../man3: File exists
cp: symlink: ../man7: File exists
cp: symlink: ../man2: File exists
cp: symlink: ../man8: File exists
cp: symlink: ../man5: File exists
cp: symlink: ../man1: File exists
cp: symlink: ../man6: File exists
cp: symlink: ../man6: File exists
cp: symlink: ../man1: File exists
cp: symlink: ../man5: File exists
cp: symlink: ../man8: File exists
cp: symlink: ../man2: File exists
cp: symlink: ../man7: File exists
cp: symlink: ../man3: File exists
cp: symlink: ../man9: File exists
cp: symlink: ../man4: File exists
cp: symlink: C: File exists
cp: symlink: C: File exists
cp: cannot overwrite directory opt/custom/var/db/etcupdate/current/usr/share/openssl/man/en.ISO8859-15 with non-directory var/db/etcupdate/current/usr/share/openssl/man/en.ISO8859-15
cp: symlink: ../man3: File exists
cp: symlink: ../man1: File exists
cp: symlink: usr/src/sys: File exists
```

**Comment by pizzamig** [comment] 2018-05-18 15:14
The first error is already fixed in trunk, but I should improve the output.
The second shouldn't happen, because the base 11.1 is already there, but the detection seems broken.
I can reproduce it, so I'll fix it ASAP.

**Closed as completed** 2018-05-18 15:22 UTC

**Comment by 0mp** [comment] 2018-05-18 15:40
Cool! I can't wait.

**Comment by 0mp** [comment] 2018-09-27 09:43
It looks like the bug is gone. Thanks!
