### ISSUE TITLE
Public bridge pots can't access neighbours

### ISSUE THREAD

**Issue by urosgruber** [pizzamig/pot#142] opened 2021-03-15 15:59 UTC
I'm not sure if this is has anything to do with pot code itself but I was under impression that public bridge is used when you want pots to talk to eachother. I've done some testing and maybe my pf rules are to restrictive but for every pot I need to specify additional rules for bridge and epair interfaces. I tried now with adding `set skip on bridge0` etc. I would love to know if there are some certain rules that need to be done as well. I've run `pot init` and I can see some things added in **/etc/pf.conf** 

I have `block return log all` right after rdr rules and then explicitly open things needed to access from the outside. and I also `pass out on etxif` at the end.

**Comment by grembo** [comment] 2021-03-15 16:05
Can you share your full /etc/pf.conf and the output of `ifconfig` on the jailhost?

**Comment by urosgruber** [comment] 2021-03-15 16:16
Here is pf.conf (I removed some variables at the top to hide some IPs)
```
ext_if="ix0"

netbios_tcp = "{ 445, 137, 138, 139 }"
netbios_udp = "{ 445, 137, 138, 139 }"
cannon_udp = "{ 8612 }"
dropbox_lan_sync_udp = "{ 17500 }"
int_tcp_services = "{ domain, ntp, smtp, www, https, ftp }"
int_udp_services = "{ domain, ntp }"
icmp_types = "{ echoreq, unreach }"

table <bruteforce> persist

set loginterface $ext_if
# set state-policy if-bound
set ruleset-optimization basic
set optimization normal
set timeout { tcp.closing 60, tcp.established 7200 }
set block-policy drop

set skip on lo0

nat-anchor pot-nat

rdr-anchor "pot-rdr/*"

### get rid quick of Internet noise like microsoft netbios service.
### This accounts to 80% of dropped traffic. We don't need to log this also
block in quick on $ext_if proto tcp from any to any port $netbios_tcp
block in quick on $ext_if proto udp from any to any port $netbios_udp
block in quick on $ext_if proto udp from any to any port $cannon_udp
block in quick on $ext_if proto udp from any to any port $dropbox_lan_sync_udp
block quick from <bruteforce>
block return log all

# ICMP (Ping, trace)
pass in quick inet proto icmp icmp-type $icmp_types no state

# SSH IN
pass in quick inet proto tcp to port $ssh_services keep state
# more defined rule
# (max-src-conn 15, max-src-conn-rate 5/3, overload <bruteforce> flush global)

# Nginx IN
pass in quick inet proto tcp from any to port { 80 443 } keep state

# Pass out everything
pass out on $ext_if
```

And the output of ifconfig
```
ix0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=e53fbb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,WOL_UCAST,WOL_MCAST,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether d0:50:99:de:6e:86
.....removed......
	media: Ethernet autoselect (10Gbase-T <full-duplex>)
	status: active
	nd6 options=8063<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL,NO_RADR,DEFAULTIF>
ix1: flags=8802<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=e53fbb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,WOL_UCAST,WOL_MCAST,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
	ether d0:50:99:de:6e:85
	media: Ethernet autoselect
	status: no carrier
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3
	inet 127.0.0.1 netmask 0xff000000
	groups: lo
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
lo1: flags=8008<LOOPBACK,MULTICAST> metric 0 mtu 16384
	options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
	groups: lo
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
pflog0: flags=141<UP,RUNNING,PROMISC> metric 0 mtu 33160
	groups: pflog
ue0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether 9e:30:07:2b:9e:f3
	nd6 options=b<PERFORMNUD,ACCEPT_RTADV,IFDISABLED>
bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether 02:b2:76:61:35:00
	inet 172.16.0.1 netmask 0xffff0000 broadcast 172.16.255.255
	id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
	maxage 20 holdcnt 6 proto stp-rstp maxaddr 2000 timeout 1200
	root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
	member: epair5a flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
	        ifmaxaddr 0 port 13 priority 128 path cost 2000
	member: epair4a flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
	        ifmaxaddr 0 port 12 priority 128 path cost 2000
	member: epair3a flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
	        ifmaxaddr 0 port 11 priority 128 path cost 2000
	member: epair2a flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
	        ifmaxaddr 0 port 10 priority 128 path cost 2000
	member: epair1a flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
	        ifmaxaddr 0 port 9 priority 128 path cost 2000
	member: epair0a flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
	        ifmaxaddr 0 port 8 priority 128 path cost 2000
	groups: bridge
	nd6 options=41<PERFORMNUD,NO_RADR>
epair0a: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=8<VLAN_MTU>
	ether 02:be:8f:a7:a0:0a
	groups: epair
	media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
	status: active
	nd6 options=4b<PERFORMNUD,ACCEPT_RTADV,IFDISABLED,NO_RADR>
epair1a: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=8<VLAN_MTU>
	ether 02:7c:81:cc:28:0a
	groups: epair
	media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
	status: active
	nd6 options=4b<PERFORMNUD,ACCEPT_RTADV,IFDISABLED,NO_RADR>
epair2a: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=8<VLAN_MTU>
	ether 02:61:3d:09:50:0a
	groups: epair
	media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
	status: active
	nd6 options=4b<PERFORMNUD,ACCEPT_RTADV,IFDISABLED,NO_RADR>
epair3a: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=8<VLAN_MTU>
	ether 02:c3:1c:2e:b9:0a
	groups: epair
	media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
	status: active
	nd6 options=4b<PERFORMNUD,ACCEPT_RTADV,IFDISABLED,NO_RADR>
epair4a: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=8<VLAN_MTU>
	ether 02:33:63:4b:8c:0a
	groups: epair
	media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
	status: active
	nd6 options=4b<PERFORMNUD,ACCEPT_RTADV,IFDISABLED,NO_RADR>
epair5a: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=8<VLAN_MTU>
	ether 02:c0:a7:dd:7f:0a
	groups: epair
	media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
	status: active
	nd6 options=4b<PERFORMNUD,ACCEPT_RTADV,IFDISABLED,NO_RADR>
```

**Comment by grembo** [comment] 2021-03-15 16:24
What about adding:

```
# poor man's antispoof on external interface
block in quick on $ext_if from 172.16/16
# pass all traffic between pots
pass from 172.16/16 to 172.16/16
```
(this is stateful by default)

**Comment by urosgruber** [comment] 2021-03-15 16:26
I guess this might work, need to try. If that is something to add I think it would be good to add in documentation. But as I said maybe my rules are to strict and default ones work fine. Let me check and see.

**Comment by urosgruber** [comment] 2021-03-15 16:49
I was aware about this but still some pots need to be restricted. I'll test this on some freshly installed machine to see if I have something on my end. Btw the above rules works for now, at least no more rules for each pot needed.

**Comment by pizzamig** [comment] 2021-03-15 18:53
Hi. The two rules added by `pot init` are the two anchors:
* a nat anchor for NAT (outbound traffic from the bridge to the NIC)
* a rdr anchor for all dynamic redirection rules (incoming traffic from the NIC to the bridge)

No restrictions are applied to the bridge, on purpose.
If you want a stronger isolation between group of `pot` (and only interested in IPv4), you can check the private bridge solution (https://pot.pizzamig.dev/Network/#network-configuration-private-bridge-virtual-network): in this case you can have separated bridges per group of `pots`

**Comment by urosgruber** [comment] 2021-03-15 20:00
So @pizzamig with fresh setup I should be able to access between pods on public bridge?

**Comment by pizzamig** [comment] 2021-03-15 20:30
yes, `pot` doesn't add any rules to separate pots on the bridge.

**Comment by grembo** [comment] 2021-03-17 13:25
> So @pizzamig with fresh setup I should be able to access between pods on public bridge?

Sorry for jumping in.

If your fresh setup doesn't have a default block rule, it will just work, but I assume even a fresh setup will have a default block in the firewall. In theory you could make use of poststart and poststop hooks to manipulate pf anchors to automate adding and removal of individual rules (adds some complexity though). I like that pot doesn't change a lot in firewall rules by default, that would be quite confusing.

**Comment by pizzamig** [comment] 2021-03-17 13:44
Hi. I think we don't know exactly what "fresh setup" means.
A vanilla FreeBSD installation has no `pf.conf`, that's what I intended as "fresh setup".
If the "fresh setup" has a `pf.conf` with the default block rule, then `pf` will block the bridge traffic.

**Comment by urosgruber** [comment] 2021-03-17 17:25
Agree. I guess while testing on my local machine I had things a bit loosen up. And public bridge worked out of the box. Maybe it would be helpfull for new commers to add write in docs about some sane defaults how to allow traffic throgh bridge. Not sure if it's just me but with all the `epair` stuff it can become quite funky so you need to skip interface name from the rule itest. But that is just from my experience.

I'm also using **hooks** to set things up in more automatic. I started with this way bofore I looked at pot project. But pot is the first one to add a bit on the `pf` side so all this was more a conversation and I think I understand the whole concept a bit more.

**Comment by pizzamig** [comment] 2021-03-24 22:00
I think we can close this issue, mainly because it's not a bug, but a potential conflict with the user pf configuration.
I'll extend the documentation to make explicit that the traffic on the bridge has to be allowed

**Closed by pizzamig** 2021-03-24 22:00 UTC
Labels: bug
